name: weather_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  percent_indicator: ^4.0.1
  get: ^4.3.8
  cupertino_icons: ^1.0.6
  json_annotation: ^4.4.0
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Add the assets section here
  assets:
    - assets/images/weather-logo.png
    - assets/images/weather-forecast(1).png
    - assets/images/weather-forecast(2).png
    - assets/images/weather-forecast(3).png
    - assets/images/weather-forecast(4).png
    - assets/images/weather-forecast(5).png
    - assets/images/weather-forecast(6).png
